# remark: pylint score formula: max(0, 0 if fatal else 10.0 - ((float(5 * error + warning + refactor + convention) / statement) * 10))
# pylint message codes:
#   R0801: duplicate-code
#   R0903: too-few-public-methods
#   R0912: too-many-branches
#   C0114: missing-module-docstring
#   C0115: missing-class-docstring
#   C0116: missing-function-docstring
#   C0301: line-too-long
#   C0413: wrong-import-position

name: Linting using pylint

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analyzing the code with pylint
      run: |
          pylint **/*.py --disable=R0801,R0903,R0912,C0114,C0115,C0116,C0301,C0413 --fail-under=9
