name: Python Applications Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: schnitzeltony/fedora-qt5:32
    steps:
      - uses: actions/checkout@v4

      - name: Echo GitHub environment
        run: |
          echo "Home: $HOME"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "CPUs: $(getconf _NPROCESSORS_ONLN)"

      - name: Test with unittest
        run: |
          cd exec-scpicmds-python
          python3 -m unittest discover

